<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="postagemPrmCpltloCP.xsl" ?>
<!-- postagemPrmCptloCP.xsl ||||  postagemSinopseCP.xsl |||| postagemSimplesCP.xsl -->
<!-- transforme com: https://www.freeformatter.com/xsl-transformer.html -->
<!DOCTYPE ebooks [
<!ELEMENT ebooks ANY>
<!ELEMENT ebooks (ebook)>
<!ELEMENT ebook (id,titulo,autor,isbn?,cat,categorias,qtdpag,sinopse,preco,linkCapa,linkSinopse,linkPrimCptlo?,linkComprar,linkRecrutamento?,hotreview?,linkPrimCptloCP?,linkSinopseCP?,linkSimplesCP?)>
<!ELEMENT categorias (categoria*)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT qtdpag (#PCDATA)>
<!ELEMENT sinopse (#PCDATA)>
<!ELEMENT preco (#PCDATA)>
<!ELEMENT linkCapa (#PCDATA)>
<!ELEMENT linkSinopse (#PCDATA)>
<!ELEMENT linkPrimCptlo (#PCDATA)>
<!ELEMENT linkComprar (#PCDATA)>
<!ELEMENT linkRecrutamento (#PCDATA)>
<!ELEMENT hotreview (#PCDATA)>
<!ELEMENT linkPrimCptloCP (#PCDATA)>
<!ELEMENT linkSinopseCP (#PCDATA)>
<!ELEMENT linkSimplesCP (#PCDATA)>

]>
	<ebooks>
		<ebook ID="505">
		<id>1</id>
		<titulo>Orgulho e Preconceito</titulo>
		<autor>Jane Austen</autor>
		<isbn>978-85-66798-18-0</isbn>
<cat>Romance, Literatura Universal, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Romance</categoria><categoria>Literatura Universal</categoria>
		</categorias>
		<qtdpag>372</qtdpag>
		<sinopse>Inglaterra, 1797. As cinco irmãs Bennet - Elizabeth, Jane, Lydia, Mary e Kitty foram criadas por uma mãe que tinha fixação em lhes encontrar maridos que garantissem seu futuro. Porém, Elizabeth deseja ter uma vida mais ampla do que apenas se dedicar ao marido, sendo apoiada pelo pai. Quando o Sr. Bingley, um solteiro rico, passa a morar em uma mansão vizinha, as irmãs logo ficam agitadas. Jane logo parece que irá conquistar o coração do novo vizinho... Jane Austen é considerada a primeira romancista moderna da literatura inglesa. Assim como em outras obras de Austen, o livro é escrito de forma satírica. "Orgulho e Preconceito", pode ser considerado como especial porque transcende o preconceito causado pelas falsas primeiras impressões e adentra no psicológico, mostrando como o auto-conhecimento pode interferir nos julgamentos errôneos...</sinopse>
		<preco>3,99</preco>
		<linkCapa>https://4.bp.blogspot.com/-5ilPIqo9oUw/XLpPaFLBp9I/AAAAAAAASCE/3zacrno_dDMwF_vwRjB0aw7b9R7cA72kQCLcBGAs/s1600/cover_minejpgOrgulhoePreconceito.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-orgulho-e-preconceito.html</linkSinopse>
		<linkPrimCptlo>http://carlosalves77.blogspot.com/2011/06/primeiro-capitulo-orgulho-e-preconceito.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C6741C</linkComprar>
		<linkRecrutamento>http://www.hotmart.com.br/recruit.html?to=9242O6762</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2011/06/primeiro-capitulo-e-preconceito-de-jane.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-orgulho-e-preconceito.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/05/orgulho-e-preconceito.html</linkSimplesCP>
		</ebook>	
		<ebook ID="524">
		<id>2</id>
		<titulo>Peter Pan</titulo>
		<autor>J. M. Barrie</autor>
		<isbn>978-85-66798-22-7</isbn>
<cat>Aventura, Infanto-Juvenil, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Aventura</categoria><categoria>Infanto-Juvenil</categoria>
		</categorias>
		<qtdpag>143</qtdpag>
		<sinopse>Estranhas folhas de árvore no chão do quarto das crianças, um menino, vestido de folhas e de limo, que aparece subitamente... Bem que a intuição da senhora Darlin lhe dizia que algo estava para acontecer. Logo, seus filhos estariam envolvidos numa incrível viagem à Terra do Nunca, onde os adultos não entram e de onde muitas crianças não voltam jamais!</sinopse>
		<preco>3,99</preco>
		<linkCapa>https://1.bp.blogspot.com/-9paajAfLcfA/XLnjMqQ56MI/AAAAAAAASAc/q3Vl6tq8WG0w691jeYA3nY6Z9TxozzYHgCLcBGAs/s1600/coverMinejpg.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-peter-pan.html</linkSinopse>
		<linkPrimCptlo>http://carlosalves77.blogspot.com/2011/06/primeiro-capitulo-peter-pan-de-j-m.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C7460C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/7497P7481</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2011/06/primeiro-capitulo-pan-de-j-m-barrie.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-peter-pan.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/05/peter-pan.html</linkSimplesCP>
		</ebook>	
		<ebook ID="527">
		<id>3</id>
		<titulo>Frankestein</titulo>
		<autor>Mary Shelley</autor>
		<isbn>978-85-66798-26-5</isbn>
<cat>Terror, Terror Gótigo, Clássico, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Terror</categoria><categoria>Terror Gótico</categoria><categoria>Clássico</categoria>
		</categorias>	
		<qtdpag>236</qtdpag>
		<sinopse>Mary Shelley (1797-1851), mulher do poeta inglês Percy B. Shelley, escreveu Frankenstein para participar de um concurso de histórias de terror realizado na intimidade do castelo de Lord Byron. Mesmo competindo com grandes gênios da literatura universal, acabou redigindo esta que é uma das mais impressionantes histórias de horror de todos os tempos. A história do dr. Victor Frankenstein e da monstruosa criatura por ele concebida vem fascinando gerações desde que foi publicada há mais de cem anos. Brilhante história de horror, escrita com fervor quase alucinatório, Frankenstein representa um dos mais estranhos florescimentos da imaginação romântica. Frankenstein, de Mary Shelley, é um dos maiores clássicos de terror da literatura em todos os tempos.</sinopse>
		<preco>3,99</preco>
		<linkCapa>https://lh3.googleusercontent.com/-9z5enA8uO0M/VexZGcDKtFI/AAAAAAAACgc/6cCjB2soby0/s512-Ic42/frankestein.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-frankestein.html</linkSinopse>
		<linkPrimCptlo>http://carlosalves77.blogspot.com/2011/06/primeiro-capitulo-frankestein-de-mary.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C7473C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/3185F7494</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2011/06/primeiro-capitulo-de-mary-shelley.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-frankestein.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/05/frankestein.html</linkSimplesCP>
		</ebook>	
		<ebook ID="541">
		<id>4</id>
		<titulo>Drácula</titulo>
		<autor>Bram Stocker</autor>
		<isbn>978-85-66798-12-8</isbn>
<cat>Terror, Ficção de Terror, Clássico, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digigal</categoria><categoria>Terror</categoria><categoria>Ficção de Terror</categoria><categoria>Clássico</categoria>
		</categorias>
		<qtdpag>196</qtdpag>
		<sinopse>Romance de 1897 escrito pelo autor irlandês Bram Stoker, tendo como protagonista o vampiro Conde Drácula. Sem dúvida trata-se do mais famoso conto de vampiros da literatura. Drácula tem sido designado como vários gêneros literários, incluindo literatura de vampiros, ficção de horror e romance gótico. Estruturalmente, é um romance epistolar, ou seja, contada como uma série de cartas, entradas de diário, registros de bordo etc. Embora Stoker não tenha inventado o vampiro, a influência do romance na popularidade dos vampiros foi singularmente responsável por muitas peças de teatro, cinema, televisão e muitas interpretações ao longo dos séculos 20 e 21.</sinopse>
		<preco>3,99</preco>
		<linkCapa>https://lh3.googleusercontent.com/-CsiFoTXtib0/VexYV3J3FeI/AAAAAAAACgM/fIHWEdDR_rw/s512-Ic42/dracula_cover.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-dracula.html</linkSinopse>
		<linkPrimCptlo>http://carlosalves77.blogspot.com/2011/06/primeiro-capitulo-dracula-de-bram.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C7646C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/1192D7667</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2011/06/primeiro-capitulo-de-bram-stocker.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-dracula.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/05/dracula.html</linkSimplesCP>
		</ebook>	
		<ebook ID="553">
		<id>5</id>
		<titulo>A Máquina do Tempo</titulo>
		<autor>H. G. Wells</autor>
		<isbn>978-85-66798-04-3</isbn>
<cat>Aventura, Ficção Científica, Literatura Universal, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Ficção Científica</categoria><categoria>Aventura</categoria><categoria>Literatura Universal</categoria>
		</categorias>	
		<qtdpag>114</qtdpag>
		<sinopse>Um cientista constrói a primeira máquina de viajar no Tempo e com ela percorre as diversas etapas da civilização humana, até chegar ao longínquo futuro, que ele supõe ser a Idade de Ouro da humanidade. O homem venceu a Natureza e o mundo inteiro é um jardim. O trabalho, as doenças, a guerra, a competição econômica e social parecem ter desaparecido. A nova raça vive exclusivamente para o amor e a diversão, ninguém envelhece. Mas como funciona essa sociedade? Quem a sustenta? De onde vêm os belos tecidos com que todos se vestem? E que são, ou quem são, esses animais noturnos que os habitantes do Mundo Superior tanto temem? Pouco a pouco, o Viajante do Tempo toma contato com a verdadeira realidade desse mundo do futuro, que de risonho e bucólico se converte num cenário de pesadelo.</sinopse>
		<preco>4,99</preco>
		<linkCapa>https://lh3.googleusercontent.com/-hPrk7msGG4M/VexX31rn1hI/AAAAAAAACf8/SJtqFPv91rA/s512-Ic42/cover.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-maquina-do-tempo.html</linkSinopse>
		<linkPrimCptlo>http://carlosalves77.blogspot.com/2011/05/primeiro-capitulo-maquina-do-tempo-de-h.html</linkPrimCptlo>
		<linkComprar>https://app.monetizze.com.br/checkout/KDV63635</linkComprar>
		<linkRecrutamento></linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2011/05/primeiro-capitulo-maquina-do-tempo-de-h.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/06/sinopse-maquina-do-tempo.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/06/a-maquina-do-tempo.html</linkSimplesCP>
		</ebook>	
		<ebook ID="560">
		<id>6</id>
		<titulo>Robinson Crusoé</titulo>
		<autor>Daniel Defoe</autor>
		<isbn>978-85-66798-23-4</isbn>
<cat>Aventura, Clássico, Literatura Universal, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Aventura</categoria><categoria>Literatura Universal</categoria><categoria>Clássico</categoria>
		</categorias>
		<qtdpag>96</qtdpag>
		<sinopse>Em Robinson Crusoé, Defoe nos oferece o mais digno conceito de educação natural. Inspirado num caso verdadeiro, o livro narra a história de um homem que se vê abandonado numa ilha deserta e que, à força da coragem e da perseverança, consegue vencer todas as dificuldades e viver feliz, mesmo longe da civilização.</sinopse>
		<preco>3,99</preco>
		<linkCapa>https://lh3.googleusercontent.com/-K-1-VnxtzIs/VexajLS0t4I/AAAAAAAACg8/mD-e_f7tnmc/s512-Ic42/RobinsonCrusoe_cover.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-robinson-crusoe.html</linkSinopse>
		<linkPrimCptlo>http://carlosalves77.blogspot.com/2011/06/primeiro-capitulo-robinson-crusoe-de.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C8138C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/4732R8159</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2011/06/primeiro-capitulo-crusoe-de-daniel.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-robinson-crusoe.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/05/robinson-crusoe.html</linkSimplesCP>
		</ebook>	
		<ebook ID="569">
		<id>7</id>
		<titulo>A Ilha do Dr Moreau</titulo>
		<autor>H. G. Wells</autor>
		<isbn>978-85-66798-03-6</isbn>
<cat>Suspense, Ficção Científica, Literatura Universal, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Ficção Científica</categoria><categoria>Suspense</categoria><categoria>Literatura Universal</categoria>
		</categorias>
		<qtdpag>140</qtdpag>
		<sinopse>Romance científico em que nos introduz em um universo fantástico povoado de seres horríveis, resultado da mente fantástica e perversa de um cientista. Edward Prendick, um jovem naturalista vítima de naufrágio, vê-se retido numa ilha do Pacífico onde o Dr. Moreau, assessorado por um assistente, leva a cabo experiência sinistras, originando criaturas incríveis, meio humanas, meio animais. E, numa situação em que o Homem assume um papel que de momento o ultrapassa, o de Criador, as consequências não tardam a manifestar-se de um modo incontrolável e inesperado.</sinopse>
		<preco>3,99</preco>
		<linkCapa>https://lh3.googleusercontent.com/-mTDNM6WgBj4/VexXudgS6gI/AAAAAAAACf0/jKH0GogBg3E/s360-Ic42/cover.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-ilha-do-dr-moreau.html</linkSinopse>
		<linkPrimCptlo>http://carlosalves77.blogspot.com/2011/05/primeiro-capitulo-ilha-do-dr-moreau-de.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C8435C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/7981A8456</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2011/05/primeiro-capitulo-ilha-do-dr-moreau-de.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-ilha-do-dr-moreau.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/05/a-ilha-do-dr-moreau.html</linkSimplesCP>
		</ebook>	
		<ebook ID="695">
		<id>8</id>
		<titulo>A Metamorfose</titulo>
		<autor>Franz Kafka</autor>
		<isbn>978-85-66798-06-7</isbn>
<cat>Drama, Literatura Fantástica, Literatura Universal, Livro Digital</cat>
		<categorias>
			<categoria>Drama</categoria><categoria>Livro Digital</categoria><categoria>Literatura Fantástica</categoria><categoria>Literatura Universal</categoria>
		</categorias>
		<qtdpag>57</qtdpag>
		<sinopse>Numa manhã, ao acordar para o trabalho, Gregor vê que se transformou num inseto horrível com um dorso duro e inúmeras patas. A princípio, as suas preocupações passam por pensamentos práticos relacionados com a sua metamorfose. Depois, as preocupações passam para um estado mais psicológico e até mesmo sentimental. Apenas a irmã se digna a levar-lhe a alimentação, mas mesmo assim a repulsa e o medo também começam a se manifestar. A metamorfose de Gregor vai além da modificação física. É sobretudo uma alteração de comportamentos, atitudes, sentimentos e opiniões.</sinopse>
		<preco>3,99</preco>
		<linkCapa>https://lh3.googleusercontent.com/-N8ZmnYwhBs8/VexaWb_xIAI/AAAAAAAACg0/-VF43G7Qjc4/s481-Ic42/AMetamorfose_cover.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-metamorfose.html</linkSinopse>
		<linkPrimCptlo>http://carlosalves77.blogspot.com/2011/05/primeiro-capitulo-metamorfose-de-franz.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C12095C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/5955A12116</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2011/05/primeiro-capitulo-metamorfose-de-franz.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-metamorfose.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/05/a-metamorfose.html</linkSimplesCP>
		</ebook>	
		<ebook ID="719">
		<id>9</id>
		<titulo>A Arte da Guerra</titulo>
		<autor>Sun Tzu</autor>
		<isbn>978-85-66798-31-9</isbn>
<cat>Ciências Humanas Sociais, Administração, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Ciências Humanas e Sociais</categoria><categoria>Administração</categoria>
		</categorias>
		<qtdpag>74</qtdpag>
		<sinopse>A Arte da Guerra é um tratado composto por treze capítulos, onde em cada capítulo é abordado um aspecto da estratégia de guerra, de modo a compor um panorama de todos os eventos e estratégias que devem ser abordados em um combate racional. Como em "O Príncipe", de Maquiavel, o livro de Sun Tzu, pode, da mesma forma, mostrar o caminho da vitória em todas as espécies de conflitos comerciais comuns, batalhas em sala de diretoria e na luta pela sobrevivência, que todos enfrentamos. São todas as formas de guerra, todas combatem sob as mesmas regras. Assim, o livro migrou das estantes dos estrategistas para as dos economistas e do administradores.</sinopse>
		<preco>4,99</preco>
		<linkCapa>https://lh3.googleusercontent.com/-SJlhQpsfD7w/VexZYczlGOI/AAAAAAAACgY/diWc6_1zp0E/s512-Ic42/a%252520arte%252520da%252520guerra.PNG</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/04/sinopse-arte-da-guerra.html</linkSinopse>
		<linkPrimCptlo>http://carlosalves77.blogspot.com/2011/06/primeiro-capitulo-arte-da-guerra-de-sun.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C12787C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/8531A12808</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2011/06/primeiro-capitulo-arte-da-guerra-de-sun.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-arte-da-guerra.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/05/a-arte-da-guerra.html</linkSimplesCP>
		</ebook>	
		<ebook ID="797">
		<id>10</id>
		<titulo>O Príncipe</titulo>
		<autor>Nicolau Maquiavel</autor>
		<isbn>978-85-66798-30-2</isbn>
<cat>Ciências Humanas Sociais, Política, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Ciências Humanas e Sociais</categoria><categoria>Política</categoria>
		</categorias>
		<qtdpag>125</qtdpag>
		<sinopse>O Príncipe, escrito em 1513, é um livro polêmico, perigoso e revolucionário. É um manual para a ação. É a obra-prima de Maquiavel, que é considerado o 'pai' da ciência política, e seus textos são estudados e analisados em escolas e universidades de todo o mundo. Trata-se de um dos tratados políticos mais fundamentais elaborados pelo pensamento humano, e que tem papel crucial na construção do conceito de Estado como modernamente conhecemos.</sinopse>
		<preco>3,99</preco>
		<linkCapa>https://lh4.googleusercontent.com/-lAzZWKtje_k/TtJ2OKDRvRI/AAAAAAAAAaQ/dUKvVs70EeA/s128/cover_principe2.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-o-principe.html</linkSinopse>
		<linkPrimCptlo>https://carlosalves77.blogspot.com/2011/06/primeiro-capitulo-o-principe-de.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C14147C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/5320O14168</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2011/06/primeiro-capitulo-o-principe-de.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-o-principe.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/05/o-principe.html</linkSimplesCP>
		</ebook>	
		<ebook ID="987">
		<id>11</id>
		<titulo>Guerra e Paz, volume 1</titulo>
		<autor>Léon Tostói</autor>
		<isbn>978-85-66798-13-5</isbn>
<cat>Romance, Literatura Estrangeira, Sociedade Russa, Guerra Napoleônica, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Romance</categoria><categoria>Literatura Estrangeira</categoria><categoria>Sociedade Russa</categoria><categoria>Guerra Napoleônica</categoria>
		</categorias>
		<qtdpag>961</qtdpag>
		<sinopse>A narração desta obra da literatura russa se passa durante a campanha de Napoleão na Áustria, a invasão da Rússia e a retirada das tropas francesas, abarcando de 1805 a 1813. Tolstoi combina romance, epopeia militar e filosofia neste livro. Um dos maiores romances jamais escritos. Trata de um imenso e detalhado painel da sociedade russa durante o tumultuado período das guerras napoleônicas. A riqueza e realismo de seus detalhes assim como suas numerosas descrições psicológicas fazem com que seja considerado um dos maiores livros da História da Literatura.<br />
Guerra e Paz criou um novo gênero de ficção. Apesar de atualmente ser considerada um romance, esta obra quebrou tantos códigos dos romances da época que diversos críticos não a consideraram como tal.</sinopse>
		<preco>3,99</preco>
		<linkCapa>https://2.bp.blogspot.com/-IKzqoZYDj4k/XLpKkrwYEGI/AAAAAAAASBg/ePYJojr0zgEaiOVIqjLz49PylX2mnIEtwCEwYBhgL/s320/minecover_guerrapaz1.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-guerra-e-paz-volume-1.html</linkSinopse>
		<linkPrimCptlo>https://carlosalves77.blogspot.com/2011/08/guerra-e-paz-volume-1.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C18502C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/4206G18523</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2019/05/primeiro-capitulo-guerra-e-paz-volume-1.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-guerra-e-paz-volume-1.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2011/08/guerra-e-paz-volume-1.html</linkSimplesCP>
		</ebook>	
		<ebook ID="988">
		<id>12</id>
		<titulo>Guerra e Paz, volume 2</titulo>
		<autor>Léon Tolstói</autor>
		<isbn>978-85-66798-14-2</isbn>
<cat>Romance, Literatura Estrangeira, Sociedade Russa, Guerra Napoleônica, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Romance</categoria><categoria>Literatura Estrangeira</categoria><categoria>Sociedade Russa</categoria><categoria>Guerra Napoleônica</categoria>
		</categorias>
		<qtdpag>1011</qtdpag>
		<sinopse>A narração desta obra da literatura russa se passa durante a campanha de Napoleão na Áustria, a invasão da Rússia e a retirada das tropas francesas, abarcando de 1805 a 1813. Tolstoi combina romance, epopeia militar e filosofia neste livro. Um dos maiores romances jamais escritos. Trata de um imenso e detalhado painel da sociedade russa durante o tumultuado período das guerras napoleônicas. A riqueza e realismo de seus detalhes assim como suas numerosas descrições psicológicas fazem com que seja considerado um dos maiores livros da História da Literatura.<br />
Guerra e Paz criou um novo gênero de ficção. Apesar de atualmente ser considerada um romance, esta obra quebrou tantos códigos dos romances da época que diversos críticos não a consideraram como tal.</sinopse>
		<preco>3,99</preco>
		<linkCapa>https://lh6.googleusercontent.com/-zhGk_A81KDU/TtJ0mE3_2MI/AAAAAAAAAZ4/qYS1xNh4VEg/s128/cover_guerrapaz2.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-guerra-e-paz-volume-2.html</linkSinopse>
		<linkPrimCptlo>https://carlosalves77.blogspot.com/2011/08/guerra-e-paz-volume-2.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C18503C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/4433G18524</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2019/05/primeiro-capitulo-guerra-e-paz-volume-2.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-guerra-e-paz-volume-2.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2011/08/guerra-e-paz-volume-2.html</linkSimplesCP>
		</ebook>	
		<ebook ID="989">
		<id>13</id>
		<titulo>Guerra e Paz, Edição Completa</titulo>
		<autor>Léon Tolstói</autor>
		<isbn>978-85-66798-13-5 e 978-85-66798-14-2</isbn>
<cat>Romance, Literatura Estrangeira, Sociedade Russa, Guerra Napoleônica, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Romance</categoria><categoria>Literatura Estrangeira</categoria><categoria>Sociedade Russa</categoria><categoria>Guerra Napoleônica</categoria>
		</categorias>
		<qtdpag>1972</qtdpag>
		<sinopse>A narração desta obra da literatura russa se passa durante a campanha de Napoleão na Áustria, a invasão da Rússia e a retirada das tropas francesas, abarcando de 1805 a 1813. Tolstoi combina romance, epopeia militar e filosofia neste livro. Um dos maiores romances jamais escritos. Trata de um imenso e detalhado painel da sociedade russa durante o tumultuado período das guerras napoleônicas. A riqueza e realismo de seus detalhes assim como suas numerosas descrições psicológicas fazem com que seja considerado um dos maiores livros da História da Literatura.<br />
Guerra e Paz criou um novo gênero de ficção. Apesar de atualmente ser considerada um romance, esta obra quebrou tantos códigos dos romances da época que diversos críticos não a consideraram como tal.</sinopse>
		<preco>5,99</preco>
		<linkCapa>https://lh4.googleusercontent.com/-k4kini-O60M/TtJ1H4w6LRI/AAAAAAAAAaA/Qhs7_0le8lo/s128/minecover_guerrapaz.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-guerra-e-paz-edicao-completa.html</linkSinopse>
		<linkPrimCptlo>https://carlosalves77.blogspot.com/2019/05/primeiro-capitulo-guerra-e-paz-edicao.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C18504C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/4510G18525</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2019/05/primeiro-capitulo-guerra-e-paz-edicao.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-guerra-e-paz-edicao-completa.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/05/guerra-e-paz-edicao-completa.html</linkSimplesCP>
		</ebook>	
		<ebook ID="1020">
		<id>14</id>
		<titulo>O Ateneu</titulo>
		<autor>Raul Pompeia</autor>
		<isbn>978-85-66798-07-4</isbn>
<cat>Romance, Literatura Nacional, Literatura Realista, Romance Impressionista, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Romance</categoria><categoria>Literatura Nacional</categoria><categoria>Romance Realista</categoria><categoria>Romance Impressionista</categoria>
		</categorias>
		<qtdpag>197</qtdpag>
		<sinopse>O Ateneu é um romance do escritor brasileiro Raul Pompeia, considerado como o único exemplar de romance impressionista na literatura brasileira. Neste livro, o personagem Sérgio, já adulto, relembra seu tempo de aluno interno no Colégio Ateneu. Misturando alegrias e tristezas, decepções e entusiasmos, o narrador pacientemente reconstrói, por meio da memória, a adolescência vivida e perdida entre as paredes do famoso internato. Este livro é um rito de passagem, um diário do menino no ambiente fechado do colégio interno...</sinopse>
		<preco>3,99</preco>
		<linkCapa>https://lh5.googleusercontent.com/-eMvGH3I3TkY/TtJyTFGKLqI/AAAAAAAAAZU/4sES1w8SvOU/s128/o_ateneu_cover.jpg</linkCapa>
		<linkSinopse>https://carlosalves77.blogspot.com/2019/05/sinopse-o-ateneu.html</linkSinopse>
		<linkPrimCptlo>http://carlosalves77.blogspot.com/2011/09/primeiro-capitulo-o-ateneu-de-raul.html</linkPrimCptlo>
		<linkComprar>https://pay.hotmart.com/C19609C</linkComprar>
		<linkRecrutamento>https://app-vlc.hotmart.com/affiliate-recruiting/view/4118O19630</linkRecrutamento>
		<hotreview></hotreview>
		<linkPrimCptloCP>https://cromossomospalavras.blogspot.com/2019/05/primeiro-capitulo-o-ateneu.html</linkPrimCptloCP>
		<linkSinopseCP>https://cromossomospalavras.blogspot.com/2019/05/sinopse-o-ateneu.html</linkSinopseCP>
		<linkSimplesCP>https://cromossomospalavras.blogspot.com/2019/05/o-ateneu.html</linkSimplesCP>
		</ebook>	
		<ebook ID="1034">
		<id>15</id>
		<titulo>Sherlock Holmes em Um Estudo em Vermelho</titulo>
		<autor>Arthur Conan Doyle</autor>
		<isbn>978-85-66798-25-8</isbn>
<cat>Romance, Policial, Suspense, Livro Digital</cat>
		<categorias>
			<categoria>Livro Digital</categoria><categoria>Romance</categoria><categoria>Policial</categoria><categoria>Suspense</categoria>
		</categorias>
		<qtdpag>135</qtdpag>